export const enhancedSticks = [
    // Group-added topics:
    'What is your favorite step (and why)?',
    'Which of the promises have come true for you?',
    'What was your miracle?',
    "How do you handle temptation?",
    "What are your strategies between meetings?",
    "How do you handle big emotions?",
    'How do you stay right-sized?',
    'Traditions',
    'Rule 62',
    'Expectations',
    'Can the order in which the Steps are worked be changed?',
    // bonus topics (source: https://www.aa.org/assets/en_us/smf-56_en.pdf):
    'Acceptance',
    'Complacency',
    'Contempt Prior to Investigation',
    'Dependence',
    'Forgiveness',
    'Freedom Through Sobriety',
    'Self-worth',
    'Inventory',
    'Letting go of Anger',
    'Making Amends',
    'Open-mindedness',
    'Participation and Action',
    'Patience and Tolerance',
    'How do you plan the action and stay out of the results?',
    'How do you practice these principles in all your affairs?',
    'Principles before personalities',
    'How do you avoid projection and living in the wreckage of the future?',
    'Staying away from the first drink',
    'Surrender',
    'Three Legacies - Recovery, Unity and Service',
    '"Twelfth stepping"',
    'Ways of carrying the AA message',
    'What is sobriety?',
    'Working with others',
    // Bonus topics from emailed source: "101 Meeting Starters A Guide to Better Twelve Step Discussions - Mel B."
    'Willpower',
    'How have I been the creator of my own misery?',
    'The Seventh Step Prayer',
    'How can you meet calamity with serenity?',
    'Be Careful What You Pray For',
    'Being Responsible',
    'Changing Things We Can',
    'Coming to Grips with Fear',
    'Coping with Depression',
    'Coping with Social Pressure',
    'Dealing with Disagreeable People',
    'Dealing with Rejection',
    'Dealing with the Past',
    'Replacing Old Ideas',
    'Finding True Independence',
    'How Do You Get Beyond People Pleasing and Trying to Arrange the Show?',
    'Giving Away to Keep It',
    'Growth through Prayer and Action',
    'Happy coincidences',
    'How to Deal with Impatience',
    'How to Find Happy Sobriety',
    'Hungry, Angry, Lonely, Tired',
    'Keep it Simple',
    'Letting go of guilt',
    'Life after the pink cloud',
    'Needing the program vs wanting it',
    'Old resentments flaring up',
    'The need for self honesty',
    'Wanting instant gratification',
    'What about my old friends?',
    'What blocks acceptance?',
    'What is being spiritually fit?',
    'When have we made a decision?',
    'Right action leads to right thinking',
    'When does pride get in your way?',
    'When have the worst thing become the best?',
    'Why do I keep coming back?',
    'Why have a primary purpose?',
    'Why is one drink so bad?',
    'Why should we make amends?',
    'Why is willingness the key?',
    'Courage to change the things we can',
];
