export const originalSticks = [
    'Step 1',
    'Step 2',
    'Step 3',
    'Step 4',
    'Step 5',
    'Step 6',
    'Step 7',
    'Step 8',
    'Step 9',
    'Step 10',
    'Step 11',
    'Step 12',
    'Fear',
    'The Promises', 
    'Guidance',
    'Service Work',
    'Easier, Softer Way',
    'Isolation',
    'Easy Does It',
    'Faith',
    'Wreckage of Past',
    'Financial Amends',
    'Honesty',
    'Humility',
    'The Newcomer',
    'Desperation',
    'Helping Others',
    'There is a Solution',
    'Serenity',
    'Going to Any Length',
    'Willingness',
    'Lack of Control',
    'Your First 30 Days',
    'Dealing with Conflict',
    'Peace',
    'Sponsorship',
    'Self-Pity',
    'Hopelessness',
    'Fellowship',
    'Courage',
    'Living Sober',
    'Spiritual Growth',
    'Attraction not Promotion',
    'Higher Power',
    'Meditation',
    'Working The Program',
    'Judgemental',
    "Higher Power's Will",
    'Love',
    'Restore to Sanity',
    'Demoralization',
    'Trusted Servants',
    'Truth',
    'Recovery',
    'Half Measures',
    'Hope',
    'Resentments',
    'Spiritual Progress',
    'Living Amends',
    'Patience',
    'Anger',
    'One Day at a Time',
    'Financial Insecurity',
    'Rigorous Honesty',
    'Jealousy',
    'Family Disease',
    'Self-Seeking',
    'Gratitude',
    'Joyous',
    'Sunlight of the Spirit',
    'First Things First',
    'Change',
    'Trudging Buddies',
    'Controversy',
    'Self-Loathing',
    'Spiritual Experience',
    'Common Solution',
    'Ego',
    'Failure',
    'Retaliation',
    'Unity',
    'Spiritual Adviser',
    'Third Step Prayer',
    'Trust',
    'New Reality'
    'Cunning, Baffling, Powerful',
    'Participation and Action'
];
