export const questions = [
    "Can the order in which the steps are worked be changed?",
    "How can you meet calamity with serenity?",
    "How do you avoid projection and living in the wreckage of the future?",
    "How do you get beyond “people pleasing” (trying to arrange the show)?",
    "How do you handle big emotions?",
    "How do you handle temptation?",
    "How do you plan the action and stay out of the results?",
    "How do you practice these principles in all your affairs?",
    "How do you stay right-sized?",
    "How have I been the creator of my own misery?",
    "What about my old friends?",
    "What are your strategies between meetings?",
    "What blocks acceptance?",
    "What is being spiritually fit?",
    "What is sobriety to you?",
    "What is your favorite step (and why)?",
    "What was your miracle?",
    "When does pride get in your way?",
    "When has the worst thing become the best?",
    "When have we made a decision?",
    "Which of the promises have come true for you?",
    "Why do I keep coming back?",
    "Why have a primary purpose?",
    "Why is one drink so bad?",
    "Why is willingness the key?",
    "Why should we make amends?",
    "Share what you're looking forward to about a random step (or your favorite part of one you've already finished)",
    "Is every area of your life manageable? How did you, or didn't you, practice step 1 recently?",
    "What are you currently working on (or resisting) giving to your HP?",
    "In what ways were you, or could you be, further 'restored to sanity'?",
    "In what ways do you (or don't you) turn your will & life over to your HP?",
    "Where did you see your HP show up today/this week/recently?",
    "Are there any recent resentments or fears in which you struggle to see your part? How do you handle that?",
    "This week, how did you (or could you) practice taking a 'fearless moral inventory'?",
    "In what ways has your sponsor or another member of the fellowship helped you?",
    "Are there any 'defects' of character you're not yet ready to have HP remove?",
    "How did you (or will you) practice humbly asking HP to remove your shortcomings?",
    "How often do you 'continue to take personal inventory'? What is your process?",
    "What did your practice of prayer & meditation look like this week? (We are not saints - how could it improve?)",
    "How has your HP given you the 'knowledge of HP's will for you and the power to carry it out'?",
    "How did you work your program in your daily life this week?",
    "Fears are big & small - how have you found courage despite fear recently?",
    "It requires no willingness to do something we WANT to do... how do you become willing to do something you DON'T want to do?",
    "In what ways did you avoid isolation & encourage true connection recently?",
    "Where were you able to practice 'easy does it' this week? Where might you practice it this coming week?",
    "How does your biggest worry today compare to your biggest worry from last week? last month? 5 years ago?",
    "What's one character *asset* of yours that showed up this week, and how?",
    "What big or small moment brought you the most serenity this week?",
    "What would you tell another alcoholic if they struggled with your biggest worry?",
    "In what ways did you try to control things this week? How did you practice letting go of control?",
    "What can you appreciate most... about the person or situation you liked the least recently?",
    "In what ways have 'esteemable acts' (big or small) helped your self-esteem?",
    "How did you practice 'first things first' recently?",
    "What does it mean to 'meet calamity with serenity'? How have you applied it to a situation in your life?",
    "How did you, or could you, practice contrary action?", 
    "How have you recently been reminded that you are not the Ultimate Authority?",
    "How did you, or could you, practice being 'fully self supporting' (financially, emotionally, spiritually)?",
    "Where did you, or could you, practice 'Rule 62' this week (not take yourself too damn seriously)? ",
    "Where did you practice acceptance this week? Where was acceptance more challenging?",
    "What big or small moment brought you the most gratitude this week?",
    "How do you practice 'principles before personalities' in meetings and in life?",
    "What does it mean to you to be a 'member' of Alcoholics Anonymous?",
    "After not drinking for a while, what other issues surfaced that needed to be dealt with: depression, anger, family relations, etc.?",
    "What is your favorite AA slogan and how has it helped you?",
    "Hope - did you lose it? Do you have it now? If no, what is blocking you?",
    "Who is your 'walking Big Book'? Why?",
    "Since recovery, what was the closest you came to drinking and, more importantly, what did you learn from it?",
    "What are you doing for the newcomer?",
    "What is currently your best tool for staying sober: meetings, steps, prayer, higher power, sponsor, slogans, phone calls, etc?",
    "Which character defect is currently causing you the most misery?",
    "Which one tripped you up the most: cunning, baffling, or powerful?",
    "Why do you keep coming back?",
    "On a daily basis, how do you deflate your ego?",
    "Which promises have come true for you?",
    "What convinced you that you had a problem?",
    "How have you changed?",
    "What is it like to be 'restored to sanity'?",
    "How did you choose your sponsor?",
    "How did you choose your home group?",
    "How does AA service help your sobriety?",
    "What's the best thing about being sober?"
];
