export const topics = [
    "Acceptance",
    "Action is key",
    "Alcoholic tornado",
    "Anger",
    "Attitude",
    "Attraction rather than promotion",
    "Be careful what you pray for",
    "Being responsible",
    "Belief in a higher power",
    "Blaming",
    "Bottles were only a symbol",
    "Came to believe",
    "Ceased fighting",
    "Change",
    "Changing things we can",
    "Character defects",
    "Coming to grips with fear",
    "Common peril, common solution",
    "Common welfare",
    "Compassion",
    "Complacency",
    "Contempt prior to investigation",
    "Controversy",
    "Coping with depression",
    "Coping with social pressure",
    "Courage",
    "Courage to change",
    "Courage to change the things we can",
    "Cunning, baffling, powerful",
    "Dealing with conflict",
    "Dealing with disagreeable people",
    "Dealing with rejection",
    "Dealing with the past",
    "Demoralization",
    "Denial",
    "Dependence",
    "Desperation",
    "Directing the show",
    "Discipline",
    "Disease",
    "Easier, softer way",
    "Easy does it",
    "Ego",
    "Emotional hangover",
    "Emotional sobriety",
    "Envy",
    "Expectations",
    "Experience, strength, and hope",
    "Failure",
    "Faith",
    "Faith without works",
    "Family disease",
    "Fear",
    "Fellowship",
    "Financial amends",
    "Financial insecurity",
    "Finding true independence",
    "First things first",
    "Fitting in",
    "Forgiveness",
    "Freedom from bondage",
    "Freedom through sobriety",
    "Giving it away to keep it",
    "Gluttony",
    "Going to any length",
    "Grandiosity",
    "Gratitude",
    "Greed",
    "Group conscience",
    "Growth through prayer and action",
    "Guidance",
    "Guilt/remorse",
    "Half measures",
    "HALT-hungry, angry, lonely, tired",
    "Happy coincidences",
    "Happy, joyous, and free",
    "Harm done to others",
    "Helping others",
    "Higher power",
    "Higher power's will",
    "Honesty",
    "Hope",
    "Hopelessness",
    "How to deal with impatience",
    "How to find happy sobriety",
    "Humility",
    "Identification as an alcoholic",
    "Insanity",
    "Integrity",
    "Intimacy",
    "Into action",
    "Inventory",
    "Isolation",
    "Jealousy",
    "Joyous",
    "Judgement",
    "Judgemental",
    "Keep it simple",
    "Lack of control",
    "Language of the heart",
    "Let go, let god",
    "Letting go of anger",
    "Letting go of guilt",
    "Life after the pink cloud",
    "Life on life's terms",
    "Live and let live",
    "Living amends",
    "Living one day at a time",
    "Living sober",
    "Love",
    "Love and tolerance",
    "Making amends",
    "Meditation",
    "Mental obsession",
    "Mental twist",
    "More will be revealed",
    "Needing the program vs wanting it",
    "New reality",
    "Now about sex…",
    "Old resentments flaring up",
    "One day at a time",
    "Open-mindedness",
    "Open Mindedness",
    "Participation and action",
    "Pass it on",
    "Patience",
    "Patience and tolerance",
    "Peace",
    "Perseverance",
    "Physical allergy",
    "Pitiful and incomprehensible demoralization",
    "Plan the action, not the result",
    "Position of neutrality",
    "Power greater than myself",
    "Powerless",
    "Practice these principles in all our affairs",
    "Prayer",
    "Pride",
    "Primary purpose",
    "Principles before personalities",
    "Progress not perfection",
    "Projection-living in the wreckage of the future",
    "Promises",
    "Psychic change",
    "Recovery",
    "Relapse",
    "Relationships",
    "Replacing old ideas",
    "Resentments",
    "Responsibility statement",
    "Restore to sanity",
    "Retaliation",
    "Right action leads to right thinking",
    "Rigorous honesty",
    "Rule 62 - Don't take yourself so damn seriously",
    "Self-centered",
    "Self-knowledge",
    "Self-loathing",
    "Self-pity",
    "Self-seeking",
    "Self-supporting",
    "Self-will",
    "Self-worth",
    "Selfishness",
    "Serenity",
    "Serenity prayer",
    "Service",
    "Service work",
    "Sloth",
    "Spiritual adviser",
    "Spiritual awakening",
    "Spiritual experience",
    "Spiritual growth",
    "Spiritual principles",
    "Spiritual progress",
    "Spirituality",
    "Sponsor",
    "Sponsorship",
    "Staying away from the first drink",
    "Step 1 - We admitted we were powerless over alcohol — that our lives had become unmanageable.",
    "Step 2 - Came to believe that a Power greater than ourselves could restore us to sanity.",
    "Step 3 - Made a decision to turn our will and our lives over to the care of God as we understood Him.",
    "Step 4 - Made a searching and fearless moral inventory of ourselves.",
    "Step 5 - Admitted to God, to ourselves, and to another human being the exact nature of our wrongs",
    "Step 6 - Were entirely ready to have God remove all these defects of character.",
    "Step 7 - Humbly asked Him to remove our shortcomings.",
    "Step 8 - Made a list of all persons we had harmed, and became willing to make amends to them all.",
    "Step 9 - Made direct amends to such people wherever possible, except when to do so would injure them or others.",
    "Step 10 - Continued to take personal inventory and when we were wrong promptly admitted it.",
    "Step 11 - Sought through prayer and meditation to improve our conscious contact with God as we understood Him, praying only for knowledge of His will for us and the power to carry that out.",
    "Step 12 - Having had a spiritual awakening as the result of these Steps, we tried to carry this message to alcoholics, and to practice these principles in all our affairs.",
    "The steps",
    "Sunlight of the spirit",
    "Surrender",
    "The family afterwards",
    "The need for self-honesty",
    "The newcomer",
    "The promises",
    "The seventh step prayer",
    "There is a solution",
    "Third step prayer",
    "Thoroughness",
    "Three legacies - recovery, unity and service",
    "Traditions",
    "Trudging buddies",
    "Trust",
    "Trusted servants",
    "Truth",
    "Understanding anonymity",
    "Unity",
    "Unmanageability",
    "Wanting instant gratification",
    "We are not a glum lot",
    "Willing to go to any length",
    "Willingness",
    "Willpower",
    "Wisdom to know the difference",
    "Working the program",
    "Working with others",
    "Wreckage of past",
    "Your first 30 days",
    "Having fun sober",
    "To thine ownself be true",
    "The first drink",
    "The last drunk",
    "The turning point",
    "But for the grace of God . . . there go I",
    "Don't quit before the miracle",
    "Handling failure",
    "Handling success",
    "I am responsible . . .",
    "This too shall pass",
    
];
