export const topics = [
    "Acceptance",
    "Action is key",
    "Alcoholic tornado",
    "Anger",
    "Attitude",
    "Attraction rather than promotion",
    "Be careful what you pray for",
    "Being responsible",
    "Belief in a higher power",
    "Blaming",
    "Bottles were only a symbol",
    "Came to believe",
    "Ceased fighting",
    "Change",
    "Changing things we can",
    "Character defects",
    "Coming to grips with fear",
    "Common peril, common solution",
    "Common welfare",
    "Compassion",
    "Complacency",
    "Contempt prior to investigation",
    "Controversy",
    "Coping with depression",
    "Coping with social pressure",
    "Courage",
    "Courage to change",
    "Courage to change the things we can",
    "Cunning, baffling, powerful",
    "Dealing with conflict",
    "Dealing with disagreeable people",
    "Dealing with rejection",
    "Dealing with the past",
    "Demoralization",
    "Denial",
    "Dependence",
    "Desperation",
    "Directing the show",
    "Discipline",
    "Disease",
    "Easier, softer way",
    "Easy does it",
    "Ego",
    "Emotional hangover",
    "Emotional sobriety",
    "Envy",
    "Expectations",
    "Experience, strength, and hope",
    "Failure",
    "Faith",
    "Faith without works",
    "Family disease",
    "Fear",
    "Fellowship",
    "Financial amends",
    "Financial insecurity",
    "Finding true independence",
    "First things first",
    "Fitting in",
    "Forgiveness",
    "Freedom from bondage",
    "Freedom through sobriety",
    "Giving it away to keep it",
    "Gluttony",
    "Going to any length",
    "Grandiosity",
    "Gratitude",
    "Greed",
    "Group conscience",
    "Growth through prayer and action",
    "Guidance",
    "Guilt/remorse",
    "Half measures",
    "HALT-hungry, angry, lonely, tired",
    "Happy coincidences",
    "Happy, joyous, and free",
    "Harm done to others",
    "Helping others",
    "Higher power",
    "Higher power's will",
    "Honesty",
    "Hope",
    "Hopelessness",
    "How to deal with impatience",
    "How to find happy sobriety",
    "Humility",
    "Identification as an alcoholic",
    "Insanity",
    "Integrity",
    "Intimacy",
    "Into action",
    "Inventory",
    "Isolation",
    "Jealousy",
    "Joyous",
    "Judgement",
    "Judgemental",
    "Keep it simple",
    "Lack of control",
    "Language of the heart",
    "Let go, let god",
    "Letting go of anger",
    "Letting go of guilt",
    "Life after the pink cloud",
    "Life on life's terms",
    "Live and let live",
    "Living amends",
    "Living one day at a time",
    "Living sober",
    "Love",
    "Love and tolerance",
    "Making amends",
    "Meditation",
    "Mental obsession",
    "Mental twist",
    "More will be revealed",
    "Needing the program vs wanting it",
    "New reality",
    "Now about sex…",
    "Old resentments flaring up",
    "One day at a time",
    "Open-mindedness",
    "Open Mindedness",
    "Participation and action",
    "Pass it on",
    "Patience",
    "Patience and tolerance",
    "Peace",
    "Perseverance",
    "Physical allergy",
    "Pitiful and incomprehensible demoralization",
    "Plan the action, not the result",
    "Position of neutrality",
    "Power greater than myself",
    "Powerless",
    "Practice these principles in all our affairs",
    "Prayer",
    "Pride",
    "Primary purpose",
    "Principles before personalities",
    "Progress not perfection",
    "Projection-living in the wreckage of the future",
    "Promises",
    "Psychic change",
    "Recovery",
    "Relapse",
    "Relationships",
    "Replacing old ideas",
    "Resentments",
    "Responsibility statement",
    "Restore to sanity",
    "Retaliation",
    "Right action leads to right thinking",
    "Rigorous honesty",
    "Rule 62",
    "Self-centered",
    "Self-knowledge",
    "Self-loathing",
    "Self-pity",
    "Self-seeking",
    "Self-supporting",
    "Self-will",
    "Self-worth",
    "Selfishness",
    "Serenity",
    "Serenity prayer",
    "Service",
    "Service work",
    "Sloth",
    "Spiritual adviser",
    "Spiritual awakening",
    "Spiritual experience",
    "Spiritual growth",
    "Spiritual principles",
    "Spiritual progress",
    "Spirituality",
    "Sponsor",
    "Sponsorship",
    "Staying away from the first drink",
    "Step 1",
    "Step 2",
    "Step 3",
    "Step 4",
    "Step 5",
    "Step 6",
    "Step 7",
    "Step 8",
    "Step 9",
    "Step 10",
    "Step 11",
    "Step 12",
    "The steps",
    "Sunlight of the spirit",
    "Surrender",
    "The family afterwards",
    "The need for self-honesty",
    "The newcomer",
    "The promises",
    "The seventh step prayer",
    "There is a solution",
    "Third step prayer",
    "Thoroughness",
    "Three legacies - recovery, unity and service",
    "Traditions",
    "Trudging buddies",
    "Trust",
    "Trusted servants",
    "Truth",
    "Understanding anonymity",
    "Unity",
    "Unmanageability",
    "Wanting instant gratification",
    "We are not a glum lot",
    "Willing to go to any length",
    "Willingness",
    "Willpower",
    "Wisdom to know the difference",
    "Working the program",
    "Working with others",
    "Wreckage of past",
    "Your first 30 days",
];
